/**
 * @file multiplayer.h
 * @brief Multiplayer communication interface -- serial-based game synchronisation.
 * @ingroup group_multiplayer
 *
 * Provides the multiplayer subsystem used to synchronise two game instances
 * over the serial port. Supports player role negotiation, game start
 * coordination, tower actions, enemy spawning, pause/resume synchronisation,
 * result selection, and connection management.
 */

#ifndef PROJ_MULTIPLAYER_H
#define PROJ_MULTIPLAYER_H

#include <stdbool.h>
#include <stdint.h>

#include "enemy_types.h"
#include "ringbuf.h"
#include "tower.h"

/**
 * @brief Available multiplayer roles.
 *
 * Each connected player must choose a unique role before the match begins.
 */
typedef enum {
  MULTIPLAYER_ROLE_NONE = 0,      /**< No role selected. */
  MULTIPLAYER_ROLE_ATTACKER = 1,  /**< Player spawns enemies. */
  MULTIPLAYER_ROLE_DEFENDER = 2,  /**< Player places and manages towers. */
} multiplayer_role_t;

/**
 * @brief Types of events generated by the multiplayer subsystem.
 *
 * Events are queued internally and can be retrieved using
 * multiplayer_next_event().
 */
typedef enum {
  MULTIPLAYER_EVENT_NONE = 0,
  MULTIPLAYER_EVENT_CONNECTED,
  MULTIPLAYER_EVENT_ROLE_CHANGED,
  MULTIPLAYER_EVENT_START_GAME,
  MULTIPLAYER_EVENT_TOWER_PLACED,
  MULTIPLAYER_EVENT_TOWER_UPGRADED,
  MULTIPLAYER_EVENT_TOWER_SOLD,
  MULTIPLAYER_EVENT_TOWER_TARGET_CHANGED,
  MULTIPLAYER_EVENT_ENEMY_SPAWNED,
  MULTIPLAYER_EVENT_PAUSE_REQUESTED,
  MULTIPLAYER_EVENT_RESUME_READY,
  MULTIPLAYER_EVENT_RESULT_ACTION,
  MULTIPLAYER_EVENT_LEAVE,
} multiplayer_event_type_t;

/**
 * @brief End-of-game actions that players may request.
 */
typedef enum {
  MULTIPLAYER_RESULT_ACTION_NONE = 0,
  MULTIPLAYER_RESULT_ACTION_RESTART = 1,
  MULTIPLAYER_RESULT_ACTION_NEXT = 2,
} multiplayer_result_action_t;

/**
 * @brief Multiplayer event structure.
 *
 * Stores the event type and any associated payload data.
 */
typedef struct {
  multiplayer_event_type_t type;
  union {
    struct {
      tower_kind_t kind;
      int16_t x;
      int16_t y;
    } tower;
    struct {
      uint16_t index;
      uint8_t level;
    } tower_upgrade;
    struct {
      uint16_t index;
    } tower_sell;
    struct {
      uint16_t index;
      uint8_t mode;
    } tower_target;
    struct {
      enemy_kind_t kind;
      uint16_t wave;
    } enemy;
    struct {
      multiplayer_result_action_t action;
    } result;
  } data;
} multiplayer_event_t;

/**
 * @brief Serial packet receiver state.
 *
 * Used internally while assembling packets received from the serial port.
 */
typedef struct {
  uint8_t state;
  uint8_t type;
  uint8_t seq;
  uint8_t len;
  uint8_t index;
  uint8_t checksum;
  uint8_t payload[8];
} multiplayer_rx_t;

/**
 * @brief Maximum number of queued multiplayer events.
 */
#define MULTIPLAYER_EVENT_QUEUE_CAP 32

/**
 * @brief Multiplayer subsystem state.
 *
 * Stores connection status, role information, synchronisation flags,
 * packet reception state, and the event queue.
 */
typedef struct {
  multiplayer_role_t local_role;
  multiplayer_role_t peer_role;
  bool peer_connected;
  bool game_started;
  bool local_resume_ready;
  bool peer_resume_ready;
  multiplayer_result_action_t local_result_action;
  multiplayer_result_action_t peer_result_action;
  uint32_t last_hello_tick;
  uint32_t last_role_tick;
  uint8_t tx_seq;
  multiplayer_rx_t rx;
  ringbuf_t event_queue;
  multiplayer_event_t event_buf[MULTIPLAYER_EVENT_QUEUE_CAP];
} multiplayer_t;

/**
 * @brief Initialise the multiplayer subsystem.
 *
 * Resets all state and prepares the receiver state machine.
 *
 * @param mp Multiplayer instance.
 */
void multiplayer_init(multiplayer_t *mp);

/**
 * @brief Start waiting for a multiplayer connection.
 *
 * Resets multiplayer state and begins connection negotiation.
 *
 * @param mp Multiplayer instance.
 */
void multiplayer_begin_wait(multiplayer_t *mp);

/**
 * @brief Mark the game as started.
 *
 * Resets pause and result synchronisation state.
 *
 * @param mp Multiplayer instance.
 */
void multiplayer_mark_game_started(multiplayer_t *mp);

/**
 * @brief Update multiplayer timers and connection logic.
 *
 * Should be called periodically from the main loop.
 *
 * @param mp Multiplayer instance.
 * @param current_tick Current system tick.
 */
void multiplayer_tick(multiplayer_t *mp, uint32_t current_tick);

/**
 * @brief Process incoming serial data.
 *
 * Reads bytes from the serial port and generates events when complete
 * packets are received.
 *
 * @param mp Multiplayer instance.
 */
void multiplayer_poll_serial(multiplayer_t *mp);

/**
 * @brief Retrieve the next queued multiplayer event.
 *
 * @param mp Multiplayer instance.
 * @param event Destination event structure.
 *
 * @return true if an event was retrieved, false otherwise.
 */
bool multiplayer_next_event(multiplayer_t *mp, multiplayer_event_t *event);

/**
 * @brief Select the local player's role.
 *
 * @param mp Multiplayer instance.
 * @param role Selected role.
 */
void multiplayer_select_role(multiplayer_t *mp, multiplayer_role_t role);

/**
 * @brief Check whether both players have selected valid roles.
 *
 * @param mp Multiplayer instance.
 *
 * @return true if both roles are assigned and distinct.
 */
bool multiplayer_roles_ready(const multiplayer_t *mp);

/**
 * @brief Get a human-readable role name.
 *
 * @param role Role identifier.
 *
 * @return Role name string.
 */
const char *multiplayer_role_name(multiplayer_role_t role);

/**
 * @brief Send a tower placement action.
 *
 * @param mp Multiplayer instance.
 * @param kind Tower type.
 * @param x Tile X coordinate.
 * @param y Tile Y coordinate.
 */
void multiplayer_send_tower(multiplayer_t *mp,
                            tower_kind_t kind,
                            int16_t x,
                            int16_t y);

/**
 * @brief Send a tower upgrade action.
 *
 * @param mp Multiplayer instance.
 * @param index Tower index.
 * @param level New upgrade level.
 */
void multiplayer_send_tower_upgrade(multiplayer_t *mp,
                                    uint16_t index,
                                    uint8_t level);

/**
 * @brief Send a tower sell action.
 *
 * @param mp Multiplayer instance.
 * @param index Tower index.
 */
void multiplayer_send_tower_sell(multiplayer_t *mp, uint16_t index);

/**
 * @brief Send a tower targeting mode change.
 *
 * @param mp Multiplayer instance.
 * @param index Tower index.
 * @param mode New targeting mode.
 */
void multiplayer_send_tower_target(multiplayer_t *mp,
                                   uint16_t index,
                                   uint8_t mode);

/**
 * @brief Send an enemy spawn action.
 *
 * @param mp Multiplayer instance.
 * @param kind Enemy type.
 * @param wave Wave number.
 */
void multiplayer_send_enemy(multiplayer_t *mp,
                            enemy_kind_t kind,
                            uint16_t wave);

/**
 * @brief Request a game pause.
 *
 * @param mp Multiplayer instance.
 */
void multiplayer_request_pause(multiplayer_t *mp);

/**
 * @brief Mark the local player as ready to resume.
 *
 * @param mp Multiplayer instance.
 */
void multiplayer_mark_local_resume_ready(multiplayer_t *mp);

/**
 * @brief Check whether both players are ready to resume.
 *
 * @param mp Multiplayer instance.
 *
 * @return true if both players are ready.
 */
bool multiplayer_both_resume_ready(const multiplayer_t *mp);

/**
 * @brief Request an end-of-game action.
 *
 * @param mp Multiplayer instance.
 * @param action Requested action.
 */
void multiplayer_request_result_action(multiplayer_t *mp,
                                       multiplayer_result_action_t action);

/**
 * @brief Check whether both players selected the same result action.
 *
 * @param mp Multiplayer instance.
 *
 * @return true if both selections match.
 */
bool multiplayer_both_result_ready(const multiplayer_t *mp);

/**
 * @brief Notify the peer that this player is leaving.
 *
 * @param mp Multiplayer instance.
 */
void multiplayer_send_leave(multiplayer_t *mp);

#endif
